### ISSUE TITLE
after Request data: No administrator could have been contacted. 

### ISSUE THREAD

**Issue by randomnickname1337** [nextcloud/data_request#10]
I have this message after i Request data:
same as by Request account deletion 

 No administrator could have been contacted. 

any idea ?

**Comment by randomnickname1337** [comment]
Hi Morris, 
all admins have emails defined, main "admin" account too.

**Comment by MorrisJobke** [comment]
cc @blizzz

**Comment by blizzz** [comment]
@randomnickname1337 add `'mail_smtpdebug' => 1,` to the config/config.php, try again, and check and post the nextcloud.log, please.

**Comment by randomnickname1337** [comment]
This is what NC Logging says:

`OCP\AppFramework\QueryException: Could not resolve OCA\External\Settings\Personal! Class OCA\External\Settings\Personal does not exist

    /var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 118: OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\External\\Se...')
    /var/www/html/nextcloud/lib/private/ServerContainer.php - line 132: OC\AppFramework\Utility\SimpleContainer->query('OCA\\External\\Se...')
    /var/www/html/nextcloud/lib/private/Settings/Manager.php - line 346: OC\ServerContainer->query('OCA\\External\\Se...')
    /var/www/html/nextcloud/lib/private/Settings/Manager.php - line 545: OC\Settings\Manager->query('OCA\\External\\Se...')
    /var/www/html/nextcloud/settings/Controller/CommonSettingsTrait.php - line 67: OC\Settings\Manager->getPersonalSettings('personal-info')
    /var/www/html/nextcloud/settings/Controller/CommonSettingsTrait.php - line 94: OC\Settings\Controller\PersonalSettingsController->formatSections(Array, 'personal-info', 'personal', 'personal')
    /var/www/html/nextcloud/settings/Controller/CommonSettingsTrait.php - line 46: OC\Settings\Controller\PersonalSettingsController->formatPersonalSections('personal', 'personal-info')
    /var/www/html/nextcloud/settings/Controller/CommonSettingsTrait.php - line 125: OC\Settings\Controller\PersonalSettingsController->getNavigationParameters('personal', 'personal-info')
    /var/www/html/nextcloud/settings/Controller/PersonalSettingsController.php - line 57: OC\Settings\Controller\PersonalSettingsController->getIndexResponse('personal', 'personal-info')
    [internal function] OC\Settings\Controller\PersonalSettingsController->index('personal-info')
    /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 161: call_user_func_array(Array, Array)
    /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 91: OC\AppFramework\Http\Dispatcher->executeController(Object(OC\Settings\Controller\PersonalSettingsController), 'index')
    /var/www/html/nextcloud/lib/private/AppFramework/App.php - line 115: OC\AppFramework\Http\Dispatcher->dispatch(Object(OC\Settings\Controller\PersonalSettingsController), 'index')
    /var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OC\\Settings\\Con...', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
    [internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
    /var/www/html/nextcloud/lib/private/Route/Router.php - line 297: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
    /var/www/html/nextcloud/lib/base.php - line 998: OC\Route\Router->match('/settings/user')
    /var/www/html/nextcloud/index.php - line 37: OC handleRequest()
    {main}`

This is what i found in nextcloud.log
`{"reqId":"9amio065Y8VaphAZ4dvj","level":1,"time":"2018-05-28T09:52:45+00:00","remoteAddr":"10.0.X.X","user":"TEST500","app":"no app in context","method":"GET","url":"\/index.php\/settings\/user","message":"Exception: {\"Exception\":\"OCP\\\\AppFramework\\\\QueryException\",\"Message\":\"Could not resolve OCA\\\\External\\\\Settings\\\\Personal! Class OCA\\\\External\\\\Settings\\\\Personal does not exist\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(118): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve('OCA\\\\\\\\External\\\\\\\\Se...')\\n#1 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/ServerContainer.php(132): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('OCA\\\\\\\\External\\\\\\\\Se...')\\n#2 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Settings\\\/Manager.php(346): OC\\\\ServerContainer->query('OCA\\\\\\\\External\\\\\\\\Se...')\\n#3 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Settings\\\/Manager.php(545): OC\\\\Settings\\\\Manager->query('OCA\\\\\\\\External\\\\\\\\Se...')\\n#4 \\\/var\\\/www\\\/html\\\/nextcloud\\\/settings\\\/Controller\\\/CommonSettingsTrait.php(67): OC\\\\Settings\\\\Manager->getPersonalSettings('personal-info')\\n#5 \\\/var\\\/www\\\/html\\\/nextcloud\\\/settings\\\/Controller\\\/CommonSettingsTrait.php(94): OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->formatSections(Array, 'personal-info', 'personal', 'personal')\\n#6 \\\/var\\\/www\\\/html\\\/nextcloud\\\/settings\\\/Controller\\\/CommonSettingsTrait.php(46): OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->formatPersonalSections('personal', 'personal-info')\\n#7 \\\/var\\\/www\\\/html\\\/nextcloud\\\/settings\\\/Controller\\\/CommonSettingsTrait.php(125): OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->getNavigationParameters('personal', 'personal-info')\\n#8 \\\/var\\\/www\\\/html\\\/nextcloud\\\/settings\\\/Controller\\\/PersonalSettingsController.php(57): OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->getIndexResponse('personal', 'personal-info')\\n#9 [internal function]: OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->index('personal-info')\\n#10 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(161): call_user_func_array(Array, Array)\\n#11 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(91): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Settings\\\\Controller\\\\PersonalSettingsController), 'index')\\n#12 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(115): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Settings\\\\Controller\\\\PersonalSettingsController), 'index')\\n#13 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OC\\\\\\\\Settings\\\\\\\\Con...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#14 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#15 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#16 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/base.php(998): OC\\\\Route\\\\Router->match('\\\/settings\\\/user')\\n#17 \\\/var\\\/www\\\/html\\\/nextcloud\\\/index.php(37): OC::handleRequest()\\n#18 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php\",\"Line\":103}","userAgent":"Mozilla\/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.181 Safari\/537.36","version":"13.0.1.1"}
{"reqId":"9amio065Y8VaphAZ4dvj","level":1,"time":"2018-05-28T09:52:45+00:00","remoteAddr":"10.0.X.X","user":"TEST500","app":"no app in context","method":"GET","url":"\/index.php\/settings\/user","message":"Exception: {\"Exception\":\"OCP\\\\AppFramework\\\\QueryException\",\"Message\":\"Could not resolve OCA\\\\External\\\\Settings\\\\Personal! Class OCA\\\\External\\\\Settings\\\\Personal does not exist\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(118): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve('OCA\\\\\\\\External\\\\\\\\Se...')\\n#1 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/ServerContainer.php(132): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('OCA\\\\\\\\External\\\\\\\\Se...')\\n#2 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Settings\\\/Manager.php(346): OC\\\\ServerContainer->query('OCA\\\\\\\\External\\\\\\\\Se...')\\n#3 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Settings\\\/Manager.php(545): OC\\\\Settings\\\\Manager->query('OCA\\\\\\\\External\\\\\\\\Se...')\\n#4 \\\/var\\\/www\\\/html\\\/nextcloud\\\/settings\\\/Controller\\\/PersonalSettingsController.php(66): OC\\\\Settings\\\\Manager->getPersonalSettings('personal-info')\\n#5 \\\/var\\\/www\\\/html\\\/nextcloud\\\/settings\\\/Controller\\\/CommonSettingsTrait.php(126): OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->getSettings('personal-info')\\n#6 \\\/var\\\/www\\\/html\\\/nextcloud\\\/settings\\\/Controller\\\/PersonalSettingsController.php(57): OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->getIndexResponse('personal', 'personal-info')\\n#7 [internal function]: OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->index('personal-info')\\n#8 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(161): call_user_func_array(Array, Array)\\n#9 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(91): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Settings\\\\Controller\\\\PersonalSettingsController), 'index')\\n#10 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(115): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Settings\\\\Controller\\\\PersonalSettingsController), 'index')\\n#11 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OC\\\\\\\\Settings\\\\\\\\Con...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#12 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#13 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#14 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/base.php(998): OC\\\\Route\\\\Router->match('\\\/settings\\\/user')\\n#15 \\\/var\\\/www\\\/html\\\/nextcloud\\\/index.php(37): OC::handleRequest()\\n#16 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php\",\"Line\":103}","userAgent":"Mozilla\/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.181 Safari\/537.36","version":"13.0.1.1"}
`

**Comment by blizzz** [comment]
@randomnickname1337 this is unrelated to data_request. The request url does not match and the problem originates from the external (sites) app.

**Comment by blizzz** [comment]
@randomnickname1337 any update?

**Comment by pieter-groeneweg** [comment]
I had a similar issue and discovered this happened as the set smtp had a self signed certificate instead of proper validated certificate.

**Comment by paulfantom** [comment]
I have the same issue using gmail as smtp.

**Comment by blizzz** [comment]
@paulfantom https://github.com/nextcloud/data_request/issues/10#issuecomment-392023304  https://github.com/nextcloud/data_request/issues/10#issuecomment-392032461

**Comment by blizzz** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please feel free to reopen.
