### ISSUE TITLE
Email comming from admin Address, not from the "nextcloud" Email

### ISSUE THREAD

**Issue by GAS85** [nextcloud/data_request#12]
Hallo,
I find out that E-Mail request is coming not from set in Settings>additional>Email e.g. nextcloud@domain or noreplay@domain, but from the Email set as Admin Email. This drives to situation when in 99,99% Email goes direct into Spam folder --> 3rd System without Authentication send me email from "me". 

What is set in settings: 

----------
![image](https://user-images.githubusercontent.com/6813635/40655759-a9140954-6342-11e8-8f70-bcbddd76e86f.png)

----------
What is coming:
![image](https://user-images.githubusercontent.com/6813635/40655694-70139e76-6342-11e8-9592-927b819000dd.png)

**Comment by blizzz** [comment]
Actually the mail sent from the is the one set by the user (if provided).

Related to #7

**Comment by GAS85** [comment]
Aha... Make no sense if user did not provide email? I expect that all emails from my NC comes from centrally configured address. May be the point is to give Admin hint about users Email? But it could be written in message body as it is done with "username".
Seems doubled, I will close it.
