### ISSUE TITLE
Does translation remain after an update?

### ISSUE THREAD

**Issue by hume1991** [nextcloud/data_request#16]
Hello, 

does translation remain after an update?
Path: /apps/data_request/l10n

Best regards

Christian Huml

**Comment by JimmyKater** [comment]
@hume1991 i think the more precise question would be: does local translation (directly in the .po-files) remain after an appupdate? right?

**Comment by rullzer** [comment]
No. They are replaces.

Please join at https://www.transifex.com/nextcloud/nextcloud/data_request/ to translate
