### ISSUE TITLE
Nextcloud 29

### ISSUE THREAD

**Issue by Moini** [nextcloud/data_request#190]
Hi - a version that is compatible with Nextcloud 28 is needed. 

Everyone who wants to be compatible with GDPR needs this app, and consequently, will have difficulties updating.

**Comment by alexanderdd** [comment]
on https://apps.nextcloud.com/apps/data_request it looks like there is an app for NC28 - so this can be closed @max-nextcloud ?

**Comment by max-nextcloud** [comment]
I'm on it.
