### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by sunjam** [nextcloud/data_request#30]
Is there any documentation on how this app works?  I'm trying to understand how a _Data Export Request_ is handled.  You click the button, enter your password, and I see no notification or clarification afterwards from the provider.  Thanks!

![Screen Shot 2019-10-04 at 12 14 54 PM](https://user-images.githubusercontent.com/1787238/66234247-0be29580-e6a2-11e9-99c0-e6c84485f829.png)

**Comment by blizzz** [comment]
from https://apps.nextcloud.com/apps/data_request:

> Administrators will be notified by email about the request.

Your provider is supposed to act upon this. Please reach out to them.
