### ISSUE TITLE
Can't click the button on old browsers (IE11, Old Edge)

### ISSUE THREAD

**Issue by mirosgold** [nextcloud/data_request#35]
Can't click the button on old browsers (IE11, Old Edge)

Works on new Edge (Chromium based) on Windows 10 1909

**Comment by blizzz** [comment]
What happens instead? Do you get any JS errors or something?

**Comment by mirosgold** [comment]
Nothing.
I see some error but I don't know if its related. I'm not a developer.
![Capture](https://user-images.githubusercontent.com/59329405/72071450-80a61b00-32f4-11ea-8b89-ea5506371fd5.PNG)

**Comment by blizzz** [comment]
It is as if  data_request/js/app.js is not loaded or executed.

**Comment by blizzz** [comment]
old browsers are not supported anymore
