### ISSUE TITLE
Message "No administrator could have been contacted."

### ISSUE THREAD

**Issue by StephanStS** [nextcloud/data_request#40]
When I push the button "Request data export" the error message shown above occurs.
Are there any further installation/setup steps necessary additional to activating the app?
Which are the requirements for this app (special user logins, special setup entries,...)?

**Comment by blizzz** [comment]
The admin should set an email address on their account.

**Comment by StephanStS** [comment]
O.k., that was my fault. No I set up the email SMTP settings and all is working fine.
Thx.
