### ISSUE TITLE
Add url in nextcloud app store

### ISSUE THREAD

**Issue by Martin-bl** [nextcloud/data_request#52]
Hello and thank you for your app. 
We are happy to use it :smiley: 
Maybe it should be usefull to add the git link (https://github.com/nextcloud/data_request ) in the Nextcloud app center : https://apps.nextcloud.com/apps/data_request

Congrats

**Comment by rugk** [comment]
While we are at it, you could also add the URL of the marketplace to the repo's about-section:
![grafik](https://user-images.githubusercontent.com/11966684/105645839-90ab8100-5e9c-11eb-8601-21f1e4e91364.png)

**Comment by max-nextcloud** [comment]
1a38cf12dd10c82703f6ec72105a3fb98a58c504 resolved this - thanks blizzz!
