### ISSUE TITLE
Can't use 'From:' user mail address when using smtp

### ISSUE THREAD

**Issue by koelle25** [nextcloud/data_request#7]
I have configured my Nextcloud instance to use SMTP for sending emails.

In [lib/Services/Request.php#L107](https://github.com/nextcloud/data_request/blob/890ee553397e10593cb617106177041fbbd4a389/lib/Services/Request.php#L107) the 'From:' address is set to the requesting user's mail address.
```
protected function craftEmailTo(IUser $admin, IEMailTemplate $template) {
	[...]
	$senderAddress = $this->requester->getEMailAddress() ?: Util::getDefaultEmailAddress('no-reply');
	$senderName = $this->requester->getEMailAddress() ? $this->requester->getDisplayName() : $defaults->getName();
	[...]
	$message->setFrom([$senderAddress => $senderName]);
	[...]
}
```
But in most situations (and also in my case) this is not possible - I get the following error (when setting `loglevel` set to _0_ (_debug_) and `smtpdebug` to _true_):
```
>> MAIL FROM:<xxx@yyy.zzz>
<< 250 2.1.0 Ok
>> RCPT TO:<aaa@bbb.ccc>
<< 553 5.7.1 <xxx@yyy.zzz>: Sender address rejected: not owned by user *****
>> RSET
<< 250 2.0.0 Ok
```
This would only be possible if the configured smtp user/server is eligible/allows sending emails with any _from_ address.

One solution could be to omit this line entirely, then the `$mailer` will use the default sender address from the NC config.php (see [OC\Mail\Mailer#L164](https://github.com/nextcloud/server/blob/01d3586a0ff930fb8fe5d05d0be98d39c5ed2a35/lib/private/Mail/Mailer.php#L164)).

Does someone know how this would behave when using send modes other than SMTP (so sendmail or PHP)?

**Comment by rullzer** [comment]
@blizzz we should just use the default mail address as provided in the nextcloud config as from address.

If a user has SPF properly configured the Nextcloud server is most likely not allowed to send any messages on behalf of that user.

Just have it from the default address. And put the e-mail of the user in the body maybe?

**Comment by blizzz** [comment]
I agree about changing the from-address, but wouldn't want to put more data than necessary in the mail. the admin can look it up anyhow. To make it less possible that someone tries to impersonate someone and trick the admin into sending data to a wrong mail address.  In that sense changing the from address is even better.
