### ISSUE TITLE
make app translatable via transifex

### ISSUE THREAD

**Issue by JimmyKater** [nextcloud/data_request#9]

**Comment by MorrisJobke** [comment]
It already is: 590905a5401c27e84cabb00e62affbdb76ee0964 - but there is nothing to translate yet ;) But it will come maybe in the next weeks. ;)

**Comment by MorrisJobke** [comment]
I forgot obviously one part: 23b448c19fe536902624c9096fb91221ba8dec81

Should show up now on transifex ;)
